# 1. Tensors

In [1]:
import torch

x = torch.empty(1) # scalar
print("empty(1): ", x)

x = torch.empty(3) # vector
print("empty(3): ", x)

x = torch.empty(2, 3) # matrix
print("emapty(2, 3): ", x)

x = torch.empty(2, 3, 4) #tensor
print("empty(2, 3, 4): ", x)

x = torch.rand(4, 8)
print("rand(4, 8): ", x)

x = torch.zeros(5, 3)
print("zeros(5, 3): ", x)

x = torch.ones(5,3)
print("ones(5, 3): ", x)

empty(1):  tensor([630479.5000])
empty(3):  tensor([1.4874e+06, 3.0907e-41, 1.5653e-42])
emapty(2, 3):  tensor([[1.4976e+06, 3.0907e-41, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 3.0914e-41]])
empty(2, 3, 4):  tensor([[[-1.6726e+06,  4.5538e-41, -1.6726e+06,  4.5538e-41],
         [ 4.4842e-44,  0.0000e+00,  1.5695e-43,  0.0000e+00],
         [ 1.9435e+21,  7.0065e-45,  8.1162e-13,  3.0914e-41]],

        [[ 1.2008e-13,  3.0914e-41, -6.1793e+32,  4.5537e-41],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])
rand(4, 8):  tensor([[0.0838, 0.6087, 0.7063, 0.8622, 0.3178, 0.1830, 0.1936, 0.1714],
        [0.6153, 0.0124, 0.8713, 0.5485, 0.1396, 0.0853, 0.1069, 0.9997],
        [0.6264, 0.6259, 0.2277, 0.2456, 0.6038, 0.8774, 0.8106, 0.2110],
        [0.8496, 0.3535, 0.2175, 0.4655, 0.5354, 0.3544, 0.1050, 0.2618]])
zeros(5, 3):  tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0

In [2]:
print("size ", x.size())
print(x.size(0))
print("shape", x.shape)
print(x.shape[0])

size  torch.Size([5, 3])
5
shape torch.Size([5, 3])
5


In [3]:
# check data type
print(x.dtype)

x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

print(x.dtype)

torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [4]:
x = torch.tensor([5.5, 3])
print(x, x.dtype)

tensor([5.5000, 3.0000]) torch.float32


In [5]:
# requires_grad argument
# this will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


### Operations with Tensors

In [6]:
x = torch.rand(6, 6)
y = torch.ones(6, 6)

# elementwise addition
z = x + y

print(x)
print(y)
print(z)

print(torch.add(x, y))
print(y.add_(x))

tensor([[0.8053, 0.8833, 0.4788, 0.8803, 0.0834, 0.2851],
        [0.5203, 0.1061, 0.6044, 0.3975, 0.5104, 0.8284],
        [0.4457, 0.7581, 0.8889, 0.1590, 0.5099, 0.3786],
        [0.9744, 0.9202, 0.1511, 0.3578, 0.7534, 0.7146],
        [0.7313, 0.6773, 0.3575, 0.3496, 0.2875, 0.0952],
        [0.7210, 0.2265, 0.4574, 0.9623, 0.2429, 0.2353]])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
tensor([[1.8053, 1.8833, 1.4788, 1.8803, 1.0834, 1.2851],
        [1.5203, 1.1061, 1.6044, 1.3975, 1.5104, 1.8284],
        [1.4457, 1.7581, 1.8889, 1.1590, 1.5099, 1.3786],
        [1.9744, 1.9202, 1.1511, 1.3578, 1.7534, 1.7146],
        [1.7313, 1.6773, 1.3575, 1.3496, 1.2875, 1.0952],
        [1.7210, 1.2265, 1.4574, 1.9623, 1.2429, 1.2353]])
tensor([[1.8053, 1.8833, 1.4788, 1.8803, 1.0834, 1.2851],
        [1.5203, 1.1061, 1.6044, 1.3975

In [7]:
print(x-y)
print(torch.sub(x, y))
print(x.sub_(y))

tensor([[-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000]])
tensor([[-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000]])
tensor([[-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1

In [8]:
print(x*y)
print(torch.mul(x,y))
print(x.mul_(y))

tensor([[-1.8053, -1.8833, -1.4788, -1.8803, -1.0834, -1.2851],
        [-1.5203, -1.1061, -1.6044, -1.3975, -1.5104, -1.8284],
        [-1.4457, -1.7581, -1.8889, -1.1590, -1.5099, -1.3786],
        [-1.9744, -1.9202, -1.1511, -1.3578, -1.7534, -1.7146],
        [-1.7313, -1.6773, -1.3575, -1.3496, -1.2875, -1.0952],
        [-1.7210, -1.2265, -1.4574, -1.9623, -1.2429, -1.2353]])
tensor([[-1.8053, -1.8833, -1.4788, -1.8803, -1.0834, -1.2851],
        [-1.5203, -1.1061, -1.6044, -1.3975, -1.5104, -1.8284],
        [-1.4457, -1.7581, -1.8889, -1.1590, -1.5099, -1.3786],
        [-1.9744, -1.9202, -1.1511, -1.3578, -1.7534, -1.7146],
        [-1.7313, -1.6773, -1.3575, -1.3496, -1.2875, -1.0952],
        [-1.7210, -1.2265, -1.4574, -1.9623, -1.2429, -1.2353]])
tensor([[-1.8053, -1.8833, -1.4788, -1.8803, -1.0834, -1.2851],
        [-1.5203, -1.1061, -1.6044, -1.3975, -1.5104, -1.8284],
        [-1.4457, -1.7581, -1.8889, -1.1590, -1.5099, -1.3786],
        [-1.9744, -1.9202, -1.1511, -1

In [9]:
print(x/y)
print(torch.div(x,y))
print(x.div_(y))

tensor([[-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000]])
tensor([[-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000]])
tensor([[-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1

In [11]:
# Slicing
x = torch.rand(7,4)
print(x)
print("x[:, 0]: ", x[:, 0]) # all rows, column 0
print("x[1, :]: ", x[1, :]) # row 1, all columns
print("x[1, 2]: ", x[1, 2]) # element at 1, 2

print(x[1, 2].item()) # get the value as a Python number


tensor([[0.1124, 0.5426, 0.6395, 0.3601],
        [0.5490, 0.8855, 0.4897, 0.8877],
        [0.8685, 0.8782, 0.2189, 0.0438],
        [0.8601, 0.7580, 0.6523, 0.5376],
        [0.3080, 0.8463, 0.9976, 0.9664],
        [0.5290, 0.0264, 0.2011, 0.1012],
        [0.0129, 0.8863, 0.8351, 0.1097]])
x[:, 0]:  tensor([0.1124, 0.5490, 0.8685, 0.8601, 0.3080, 0.5290, 0.0129])
x[1, :]:  tensor([0.5490, 0.8855, 0.4897, 0.8877])
x[1, 2]:  tensor(0.4897)
0.4896906614303589


In [12]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### Numpy

In [14]:
a = torch.ones(10)
print(a)

b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [16]:
# Careful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other

a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
c = torch.tensor(a)
print(a)
print(b)
print(c)

# again be careful when modifying
a += 1
print(a)
print(b)
print(c)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


## GPU support

By default all tensors are created on the CPU. But you can also move them to the GPU (if it's available), or create them directly on the GPU

In [19]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.rand(2,2).to(device)

x = torch.rand(2, 2, device=device)