# 1. Tensors

In [ ]:
import torch

x = torch.empty(1) # scalar
print("empty(1): ", x)

x = torch.empty(3) # vector
print("empty(3): ", x)

x = torch.empty(2, 3) # matrix
print("emapty(2, 3): ", x)

x = torch.empty(2, 3, 4) #tensor
print("empty(2, 3, 4): ", x)

x = torch.rand(4, 8)
print("rand(4, 8): ", x)

x = torch.zeros(5, 3)
print("zeros(5, 3): ", x)

x = torch.ones(5,3)
print("ones(5, 3): ", x)

empty(1):  tensor([1.7357e-31])
empty(3):  tensor([ 2.8833e-13,  3.1997e-41, -1.2294e+22])
emapty(2, 3):  tensor([[ 3.3562e-13,  3.1997e-41,  3.3557e-13],
        [ 3.1997e-41, -1.5303e+06,  4.5616e-41]])
empty(2, 3, 4):  tensor([[[-1.8627e+05,  4.5616e-41,  0.0000e+00,  1.4013e-45],
         [ 3.3549e-13,  3.1997e-41,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  3.3557e-13,  3.1997e-41]],

        [[ 4.9350e-14,  3.1997e-41,  1.9591e-31,  4.5616e-41],
         [ 0.0000e+00,  0.0000e+00,  1.5835e-43,  0.0000e+00],
         [ 3.3550e-13,  3.1997e-41, -1.2294e+22,  4.5616e-41]]])
rand(4, 8):  tensor([[0.3369, 0.6982, 0.0066, 0.6000, 0.5754, 0.8987, 0.2904, 0.1334],
        [0.0030, 0.4360, 0.5957, 0.8916, 0.5120, 0.3116, 0.2630, 0.5297],
        [0.3880, 0.1007, 0.7503, 0.0039, 0.0323, 0.1878, 0.7672, 0.1629],
        [0.6059, 0.1205, 0.4017, 0.2237, 0.5240, 0.2335, 0.3116, 0.5997]])
zeros(5, 3):  tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
      

In [ ]:
print("size ", x.size())
print(x.size(0))
print("shape", x.shape)
print(x.shape[0])

size  torch.Size([5, 3])
5
shape torch.Size([5, 3])
5


In [ ]:
# check data type
print(x.dtype)

x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

print(x.dtype)

torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [ ]:
x = torch.tensor([5.5, 3])
print(x, x.dtype)

tensor([5.5000, 3.0000]) torch.float32


In [ ]:
# requires_grad argument
# this will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


### Operations with Tensors

In [ ]:
x = torch.rand(6, 6)
y = torch.ones(6, 6)

# elementwise addition
z = x + y

print(x)
print(y)
print(z)

print(torch.add(x, y))
print(y.add_(x))

tensor([[0.8064, 0.1795, 0.6332, 0.9965, 0.6983, 0.1275],
        [0.7892, 0.0318, 0.1465, 0.4468, 0.2255, 0.0157],
        [0.4931, 0.6420, 0.6165, 0.0586, 0.0433, 0.5127],
        [0.4762, 0.5397, 0.0018, 0.7558, 0.0101, 0.5114],
        [0.6396, 0.6475, 0.0324, 0.2182, 0.0880, 0.1593],
        [0.9941, 0.1050, 0.2956, 0.7594, 0.9540, 0.0315]])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
tensor([[1.8064, 1.1795, 1.6332, 1.9965, 1.6983, 1.1275],
        [1.7892, 1.0318, 1.1465, 1.4468, 1.2255, 1.0157],
        [1.4931, 1.6420, 1.6165, 1.0586, 1.0433, 1.5127],
        [1.4762, 1.5397, 1.0018, 1.7558, 1.0101, 1.5114],
        [1.6396, 1.6475, 1.0324, 1.2182, 1.0880, 1.1593],
        [1.9941, 1.1050, 1.2956, 1.7594, 1.9540, 1.0315]])
tensor([[1.8064, 1.1795, 1.6332, 1.9965, 1.6983, 1.1275],
        [1.7892, 1.0318, 1.1465, 1.4468

In [ ]:
print(x-y)
print(torch.sub(x, y))
print(x.sub_(y))

tensor([[-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000]])
tensor([[-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000]])
tensor([[-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1

In [ ]:
print(x*y)
print(torch.mul(x,y))
print(x.mul_(y))

tensor([[-1.8064, -1.1795, -1.6332, -1.9965, -1.6983, -1.1275],
        [-1.7892, -1.0318, -1.1465, -1.4468, -1.2255, -1.0157],
        [-1.4931, -1.6420, -1.6165, -1.0586, -1.0433, -1.5127],
        [-1.4762, -1.5397, -1.0018, -1.7558, -1.0101, -1.5114],
        [-1.6396, -1.6475, -1.0324, -1.2182, -1.0880, -1.1593],
        [-1.9941, -1.1050, -1.2956, -1.7594, -1.9540, -1.0315]])
tensor([[-1.8064, -1.1795, -1.6332, -1.9965, -1.6983, -1.1275],
        [-1.7892, -1.0318, -1.1465, -1.4468, -1.2255, -1.0157],
        [-1.4931, -1.6420, -1.6165, -1.0586, -1.0433, -1.5127],
        [-1.4762, -1.5397, -1.0018, -1.7558, -1.0101, -1.5114],
        [-1.6396, -1.6475, -1.0324, -1.2182, -1.0880, -1.1593],
        [-1.9941, -1.1050, -1.2956, -1.7594, -1.9540, -1.0315]])
tensor([[-1.8064, -1.1795, -1.6332, -1.9965, -1.6983, -1.1275],
        [-1.7892, -1.0318, -1.1465, -1.4468, -1.2255, -1.0157],
        [-1.4931, -1.6420, -1.6165, -1.0586, -1.0433, -1.5127],
        [-1.4762, -1.5397, -1.0018, -1

In [ ]:
print(x/y)
print(torch.div(x,y))
print(x.div_(y))

tensor([[-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000]])
tensor([[-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000]])
tensor([[-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -1.0000, -1

In [ ]:
# Slicing
x = torch.rand(7,4)
print(x)
print("x[:, 0]: ", x[:, 0]) # all rows, column 0
print("x[1, :]: ", x[1, :]) # row 1, all columns
print("x[1, 2]: ", x[1, 2]) # element at 1, 2

print(x[1, 2].item()) # get the value as a Python number


tensor([[0.1416, 0.1052, 0.0698, 0.7811],
        [0.0465, 0.5634, 0.2584, 0.2393],
        [0.8958, 0.6712, 0.3480, 0.2870],
        [0.3893, 0.8249, 0.9273, 0.6145],
        [0.6268, 0.8540, 0.5882, 0.4393],
        [0.9038, 0.8544, 0.1495, 0.4251],
        [0.6646, 0.9844, 0.7246, 0.8458]])
x[:, 0]:  tensor([0.1416, 0.0465, 0.8958, 0.3893, 0.6268, 0.9038, 0.6646])
x[1, :]:  tensor([0.0465, 0.5634, 0.2584, 0.2393])
x[1, 2]:  tensor(0.2584)
0.2584496736526489


In [ ]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### Numpy

In [ ]:
a = torch.ones(10)
print(a)

b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [ ]:
# Careful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other

a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
c = torch.tensor(a)
print(a)
print(b)
print(c)

# again be careful when modifying
a += 1
print(a)
print(b)
print(c)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


## GPU support

By default all tensors are created on the CPU. But you can also move them to the GPU (if it's available), or create them directly on the GPU

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.rand(2,2).to(device)

x = torch.rand(2, 2, device=device)

# Autograd

The autograd package provides automatic differentiation for all operations on Tensors. Generally speaking, *torch.autograd* is an engine for computing the vector-Jacobian product. It computes partial derivates while applying the chain rule.

Set `requires_grad = True`:

In [ ]:
import torch

x = torch.randn(3, requires_grad= True)
y = x + 2

# y was created as a result of an operation, so it has a grad_fn attribute.
# grad_fn: references a Function that has created the Tensor
print(x) # created by the user -> grad_fn is None
print(y)
print(y.grad_fn)

tensor([ 0.0483, -0.0498, -0.6530], requires_grad=True)
tensor([2.0483, 1.9502, 1.3470], grad_fn=<AddBackward0>)


In [ ]:
z = y * y * y * 85
print(z)
z = z.mean()
print(z)

tensor([730.4238, 630.4799, 207.7303], grad_fn=<MulBackward0>)
tensor(522.8781, grad_fn=<MeanBackward0>)


In [ ]:
# Let's compute the gradients with backpropagation
# When we finish our computation we can call .backward() and have all the gradients computed automatically.
# The gradient for this tensor will be accumulated into .grad attribute.
# It is the partial derivate of the function w.r.t. the tensor

print(x.grad)
z.backward()
print(x.grad)

None
tensor([356.6068, 323.2862, 154.2196])


# Stop a tensor from tracking history:



For example during the training loop when we want to update our weights, or after training during evaluation. These operations should not be part of the gradient computation. To prevent this, we can use:

- `x.requires_grad_(False)`
- `x.detach()`
- wrap in `with torch.no_grad():`

In [ ]:
# requires_grad_() changes an existing flag in-place.
a = torch.randn(6, 6)
b = (a * a).sum()
print(a.requires_grad)
print(b.grad_fn)

a.requires_grad_(True)
b = (a * a).sum()
print(a.requires_grad)
print(b.grad_fn)

False
None
True


In [ ]:
# .detach(): get a new Tensor with the same content but no gradient computation.
a = torch.randn(3, 4, requires_grad=True)
b = a.detach()
print(a.requires_grad)
print(b.requires_grad)

True
False


In [ ]:
# wrap in "with torch.no_grad():"
a = torch.randn(2, 2, requires_grad=True)
print(a.requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

True
False


## Gradient Descent Autograd

Linear Regression example:

$f(x) = w * x  + b$

here: `f(x) = 2 *x `

In [ ]:
import torch

# Linear regression
# f = w *x + b
# here: f = 2 * x

X = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8, 10, 12, 14, 16], dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)#

# model output
def forward(x):
  return w * x

# loss = MSE
def loss(y, y_pred):
  return ((y_pred - y)**2).mean()

X_test = 15.0

print(f'Prediction before training: f({X_test}) = {forward(X_test).item():.3f}')

Prediction before training: f(15.0) = 0.000


In [ ]:
# Training
learning_rate = 0.01
n_epochs = 100

for epoch in range(n_epochs):
  # predict = forward_pass
  y_pred = forward(X)

  l = loss(Y, y_pred)

  # claculate gradients = backward pass
  l.backward() # dl/dw

  # update weights
  with torch.no_grad():
    w -= learning_rate * w.grad

    # zero the gradients after updating
    w.grad.zero_()

    if (epoch+1) % 10 == 0:
      print(f'epoch {epoch+1}: w = {w.item():.3f}, loss = {l.item():.3f}')

print(f'Prediction after training: f({X_test}) = {forward(X_test).item():.3f}')

epoch 10: w = 1.998, loss = 0.000
epoch 20: w = 2.000, loss = 0.000
epoch 30: w = 2.000, loss = 0.000
epoch 40: w = 2.000, loss = 0.000
epoch 50: w = 2.000, loss = 0.000
epoch 60: w = 2.000, loss = 0.000
epoch 70: w = 2.000, loss = 0.000
epoch 80: w = 2.000, loss = 0.000
epoch 90: w = 2.000, loss = 0.000
epoch 100: w = 2.000, loss = 0.000
Prediction after training: f(15.0) = 30.000


# Model, Loss & Optimizer

In [7]:
import torch
import torch.nn as nn

X  = torch.tensor([[1], [2], [3], [4], [5],[6], [7], [8]], dtype=torch.float32)
Y = torch.tensor([[2], [4], [6], [8], [10], [12], [14], [16]], dtype=torch.float32)

n_samples, n_features = X.shape
print(f'n_samples: {n_samples}, n_features = {n_features}')

# Create a test sample
X_test = torch.tensor([15], dtype=torch.float32)

n_samples: 8, n_features = 1


In [8]:
class LinearRegression(nn.Module):
  def __init__(self, input_dim, output_dim):
    super(LinearRegression, self).__init__()
    self.lin = nn.Linear(input_dim, output_dim)

  def forward(self, x):
    return self.lin(x)


input_size, output_size = n_features, n_features
model = LinearRegression(input_size, output_size)

print(f'Prediction before training: f({X_test.item()}) = {model(X_test).item():.3f}')

learning_rate = 0.01
n_epochs = 100

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(n_epochs):
  y_predicted = model(X)

  l = loss(Y, y_predicted)

  l.backward()

  optimizer.step()

  optimizer.zero_grad()

  if (epoch+1) % 10 == 0:
    w, b = model.parameters()
    print('epoch ', epoch+1, ': w =', w[0][0].item(), ' loss = ', l.item())

print(f'Prediction after training: f({X_test.item()}) = {model(X_test).item():.3f}')

Prediction before training: f(15.0) = -5.221
epoch  10 : w = 1.9670073986053467  loss =  0.006793336942791939
epoch  20 : w = 1.9695653915405273  loss =  0.006077717524021864
epoch  30 : w = 1.970759630203247  loss =  0.005610410589724779
epoch  40 : w = 1.971906304359436  loss =  0.005179037339985371
epoch  50 : w = 1.9730077981948853  loss =  0.0047808000817894936
epoch  60 : w = 1.9740662574768066  loss =  0.004413210321217775
epoch  70 : w = 1.975083351135254  loss =  0.004073879681527615
epoch  80 : w = 1.976060390472412  loss =  0.00376063771545887
epoch  90 : w = 1.9769991636276245  loss =  0.0034714911598712206
epoch  100 : w = 1.9779011011123657  loss =  0.0032045587431639433
Prediction after training: f(15.0) = 29.793
